library(misoR)
local({
  close <- function(a, b) stopifnot(isTRUE(all.equal(a, b, tolerance = 1e-8)))
  rejects <- function(expr) stopifnot(inherits(tryCatch(force(expr), error = identity), "error"))
  set.seed(41)
  Y <- matrix(rpois(20 * 12, 1), 20, 12)
  F <- matrix(rexp(3 * 12), 3, 12)
  ps <- poisson_susie_fit(Y, F, D = 2, max_iters = 5, seed = 4)
  fresh <- miso_init(Y, F, D = 2, susie_max_iters = 5, seed = 4,
                    phi0 = 0.2, keep_intermediates = TRUE)
  cached <- miso_init(Y, poisson_susie = ps, phi0 = 0.2)
  fields <- c("F", "gamma", "alpha0", "beta0", "omega", "phi0", "support")
  close(fresh[fields], cached[fields])
  close(fresh$poisson_susie, ps)
  stopifnot(cached$settings$reused_poisson_susie)
  fit <- miso_fit(Y, init = cached, max_iters = 4, tol = 0)
  close(fit$phi0, cached$phi0)
  override <- miso_fit(Y, init = cached, phi0 = 0.3, max_iters = 1)
  close(override$phi0, rep(0.3, ncol(fit$omega)))
  sparse <- miso_fit(Matrix::Matrix(Y, sparse = TRUE), init = cached, max_iters = 4, tol = 0)
  close(predict(fit), predict(sparse))
  close(predict(fit), predict(fit, type = "loadings") %*% fit$F)
  rejects(miso_init(Y[-1, ], poisson_susie = ps))
  rejects(miso_init(Y, poisson_susie = ps, D = 3))
  rejects(miso_init(Y, F = F + 1, poisson_susie = ps))
  rejects(predict(fit, newdata = Y))
  sm <- summary(fit)
  stopifnot(inherits(sm, "summary.miso_fit"), sum(sm$motifs$n_assigned) == nrow(Y),
            sm$final_elbo == tail(fit$elbo, 1), sm$elbo_decreases == 0,
            nrow(sm$slots) == dim(fit$gamma)[1] * dim(fit$gamma)[2])
  for (j in seq_len(nrow(sm$slots))) {
    slot <- sm$slots[j, ]
    close(slot$probability, fit$gamma[slot$motif, slot$slot, slot$factor])
    close(slot$prior_mean, fit$prior_mean[slot$motif, slot$slot])
  }
  invisible(capture.output(print(sm)))
  path <- tempfile(fileext = ".pdf")
  grDevices::pdf(path)
  on.exit({ grDevices::dev.off(); unlink(path) }, add = TRUE)
  plot(fit)
  order_clusters <- rev(sort(unique(fit$z_hat)))
  data <- plot(fit, type = "loadings", factor_order = 3:1,
               cluster_order = order_clusters, sort_by = 1)
  close(rowSums(data$values), rep(1, nrow(Y)))
  close(data$loadings, predict(fit, "loadings"))
  stopifnot(identical(sort(data$observation_order), seq_len(nrow(Y))),
            identical(data$factor_order, 3:1), identical(data$cluster_order, order_clusters))
  counts <- plot(fit, type = "loadings", normalize = FALSE)
  close(counts$values, counts$loadings[counts$observation_order, , drop = FALSE])
  rejects(plot(fit, type = "loadings", factor_order = c(1, 1, 3)))
  rejects(plot(fit, type = "loadings", cluster_order = 0))
  rejects(plot(fit, type = "loadings", normalize = NA))
  single <- miso_fit(matrix(0, 1, 1), F = matrix(1), D = 1, max_iters = 2)
  plot(single)
  data <- plot(single, type = "loadings")
  stopifnot(identical(dim(data$loadings), c(1L, 1L)), nrow(summary(single)$slots) == 1)
})
cat("Initialization, summary, prediction, and plot API tests passed.\n")
