library(misoR)
set.seed(12)
F <- rbind(c(5, 4, 1, 1, 1, 1), c(1, 1, 5, 4, 1, 1), c(1, 1, 1, 1, 5, 4))
F <- F / rowSums(F)
N <- 60L
L <- matrix(0, N, 3)
L[, 1] <- rgamma(N, 3, rate = 0.15)
L[cbind(seq_len(N), rep(2:3, each = N / 2))] <- rgamma(N, 3, rate = 0.15)
Y <- matrix(rpois(N * ncol(F), as.vector(L %*% F)), N, ncol(F))
initial <- miso_init(Y, F = F, D = 2)
fit <- miso_fit(Y, init = initial, max_iters = 100)
print(summary(fit))
plot(fit, type = "elbo")
plot(fit, type = "loadings", sort_by = 1)
